### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [dead8309/Kizzy#180] opened 2023-05-28 19:37 UTC
**Describe the bug**
I installed the app and im trying to set a custom presence.. but its not working. i can't see the presence on my other device...

**To Reproduce**
1. Go to '....'

**Expected behavior**
To Make a rich presence on my discord acc.

**Screenshots**

**Please complete the following information:**
 - Device: [Samsung a33 5g]
 - OS: [android 13]
 - Kizzy Version [4.6]

**Additional context**

**Comment by dead8309** [comment] 2023-05-28 19:54
Can you provide some screenshots of your custom rpc config and logs screen

**Comment by TeaEndsAcronyms** [comment] 2023-05-28 20:27
Custom RPC: ![Screenshot_20230528_232645_Kizzy.jpg](https://github.com/dead8309/Kizzy/assets/123305689/c5e650b5-4ae2-4c4e-a82f-a1455ae9997c)

Logs: ![Screenshot_20230528_232704_Kizzy.jpg](https://github.com/dead8309/Kizzy/assets/123305689/db5b9fe3-9991-46cc-8146-b434866d2b52)

**Comment by dead8309** [comment] 2023-05-28 22:02
Provide **full** screenshot of custom rpc screen

**Comment by andrewdevcup** [comment] 2023-05-31 00:49
> Provide **full** screenshot of custom rpc screen

A friend also had a similar issue recently and i asked her for some screenshots.
She enabled App Detection and selected some games, it's not showing up on Discord.
![image](https://github.com/dead8309/Kizzy/assets/60042213/90660a15-afeb-4022-bfdb-ae1da1ed406d)
![image](https://github.com/dead8309/Kizzy/assets/60042213/24b346f0-ff0d-4f8b-9d05-95c58a643589)

I've also been working on an RPC script for another project of mine, and i know that the socket doesn't just close like that, if it does it shows a 40XX error.
Testing with the browser, it seems to be something related to the socket and internet connection (is it the gateway address?).
(Also, i have to give you a huge thanks for the complete documentation on the activity stuff, i couldn't find it anywhere, thank you, Thank You!)

**Comment by dead8309** [comment] 2023-05-31 03:06
Code 1000 is a normal closure, it happens:
* If you manually switch off the rpc
* Android system shuts down the app to release memory

If your phone is closing the app then you can try disabling battery restrictions for kizzy app

**Comment by andrewdevcup** [comment] 2023-05-31 03:56
> Code 1000 is a normal closure, it happens:
> 
> * If you manually switch off the rpc
> * Android system shuts down the app to release memory
> 
> If your phone is closing the app then you can try disabling battery restrictions for kizzy app

I've been doing some tests on my phone and sometimes things will just deactivate when switching apps, and enabling Apps Detection won't start the service until Custom RPC is enabled (Apps Detection won't show the gateway logs until the Custom RPC is enabled first, which does connect to the gateway), and after switching apps and testing some more, it finally saved the state and now it kinda works as it should

**Comment by dead8309** [comment] 2023-05-31 04:02
Apps rpc doesn't run gateway indefinitely.If a selected app is detected then it **starts** the gateway and set presence and once that app is no longer running, gateway gets **closed**.

This is done to avoid consuming battery

**Comment by andrewdevcup** [comment] 2023-05-31 04:09
> Apps rpc doesn't run gateway indefinitely.If a selected app is detected then it **starts** the gateway and set presence and once that app is no longer running, gateway gets **closed**.
> 
> This is done to avoid consuming battery

I know, and that was a great idea, i'm just saying that, that service doesn't start as soon as you enable Apps Detection, unless Custom RPC is enabled first and you play with its settings a little (happened twice already on two different devices)
That also happened on the first and second run of the app though, after that, it does work like normal.

**Comment by dead8309** [comment] 2023-05-31 05:06
> I know, and that was a great idea, i'm just saying that, that service doesn't start as soon as you enable Apps Detection

That's what I was saying, that rpc in app detection will only start once it detects the app, not from the starting the service

**Comment by andrewdevcup** [comment] 2023-05-31 17:05
> 
> That's what I was saying, that rpc in app detection will only start once it detects the app, not from the starting the service

The issue i have is with the service rather than the gateway socket.
When you enable Apps Detection first, the service (and so this notification) won't show up, doesn't matter if you re-open the app, it just won't for some reason.
But, once enabling Custom RPC (which does show the service notification for it), and enabling Apps Detection again, it does show the notification, **regardless of choosing and starting any selected app.**
Again, this issue only happened to me on the first and second launch of the Kizzy app.
If i had to guess it's just Android having trouble starting a service for whatever reason, it happened to me while i was testing apps in the past.
![image](https://github.com/dead8309/Kizzy/assets/60042213/93b70dab-9d05-4c9b-bc75-0dd0c9fe179a)

**Comment by dead8309** [comment] 2023-05-31 17:27
> If i had to guess it's just Android having trouble starting a service for whatever reason, it happened to me while i was testing apps in the past.

Then it's your device issue, nothing much i can do about it

**Comment by andrewdevcup** [comment] 2023-05-31 17:45
> > If i had to guess it's just Android having trouble starting a service for whatever reason, it happened to me while i was testing apps in the past.
> 
> Then it's your device issue, nothing much i can do about it

How about my other device, TeaEndsAcronyms's device, and my friend's device?
More info i can provide, i have Android 12, they have Android 13, and my other device has Android 8

**Comment by andrewdevcup** [comment] 2023-05-31 17:47
Suggestion: Check if service is running when enabling any RPC option, after some time if it's not running and not cancelled by the user, restart it automatically, or give the user a warning

**Comment by andrewdevcup** [comment] 2023-05-31 17:50
After telling her the steps i did to fix it, now it works for her.
![image](https://github.com/dead8309/Kizzy/assets/60042213/e251c9ad-1d31-455e-83f2-463b17dd42fc)

**Comment by dead8309** [comment] 2023-05-31 18:37
> Suggestion: Check if service is running when enabling any RPC option, after some time if it's not running and not cancelled by the user, restart it automatically, or give the user a warning

It already does that 
https://github.com/dead8309/Kizzy/blob/63731b8cddf35cdbf5c54be00e7b6572f7793ff7/feature_apps_rpc/src/main/java/com/my/kizzy/feature_apps_rpc/AppsRpc.kt#L104-L112

**Comment by dead8309** [comment] 2023-05-31 18:39
Closing this as you are not providing
* Logs which states there's any bug or crash
* Steps to reproduce this issue

**Comment by andrewdevcup** [comment] 2023-05-31 18:42
>
> It already does that 

That's what i've assumed looking at the logs but, i'm talking about calling ctx.startService a second time if the service itself it's not running, like a second after

**Comment by andrewdevcup** [comment] 2023-05-31 18:46
> Closing this as you are not providing
> 
> * Logs which states there's any bug or crash
> * Steps to reproduce this issue

Wait but i did it for him, if you can just start the app in an emulator and only enabling App Detection and testing if it appears on Discord

**Comment by andrewdevcup** [comment] 2023-05-31 19:05
> 
> I already did that a couple of times, even tried on my phone

I'll try to reproduce the issue consistantly and send a video clip

**Comment by dead8309** [comment] 2023-05-31 19:16
Sure

**Comment by dead8309** [comment] 2023-06-01 01:39
> 
The issue was not related to gateway neither the service, the service started instantly as you can see the notification icon on status bar. The actual problem was you selecting the app `after` enabling apps rpc . You have to select the apps `before` launching service

**Comment by andrewdevcup** [comment] 2023-06-01 14:15
> > 
> 
> The issue was not related to gateway neither the service, the service started instantly as you can see the notification icon on status bar. The actual problem was you selecting the app `after` enabling apps rpc . You have to select the apps `before` launching service

Which may be kind of counterintuitive since the App Detection switch appears before you can see your apps.
If your service can only start with certain data then, restart the service every time a new app is selected after enabling apps rpc.

Wait, does that mean if you enable other apps while Apps Detection is active, they won't show up until disabled and enabled again?

**Comment by dead8309** [comment] 2023-06-01 14:26
> Which may be kind of counterintuitive since the App Detection switch appears before you can see your apps.

It's there so people can quickly start/stop services.

> Wait, does that mean if you enable other apps while Apps Detection is active, they won't show up until disabled and enabled again?

The enabled apps data is stored in preferences, and it's not very efficient to repeatedly read the data from JSON and convert it into data classes every 5 seconds. Therefore, it would be more efficient to retrieve and process the data once at the start of the service rather than inside the loop."

**Comment by andrewdevcup** [comment] 2023-06-01 14:45
> The enabled apps data is stored in preferences, and it's not very efficient to repeatedly read the data from JSON and convert it into data classes every 5 seconds. Therefore, it would be more efficient to retrieve and process the data once at the start of the service rather than inside the loop."

Alright, so, if efficiency is the concern then, for the user experience, at least add a popup saying "Please select an app before enabling App Detection, do this for any new app you want to add." If no apps are selected, the enable button just makes you go to the app list, a feedback animation would be nice (it'll be better than MIUI).
Although restarting the service for selecting any new app also works.
It's all just for the sake of comfort using the app, fancy good looking UIs.

Idk very well how is your service structure, but if you could, send the JSON data from the app to the service every time the app is put in background, the service is enabled and app selection has been changed.

**Comment by dead8309** [comment] 2023-06-01 14:49
Not prioritising this as I am busy with other stuffs however if you wish you can make a pr with the said changes.

**Closed** 2023-06-04 09:52 UTC
Labels: enhancement, help wanted
