### ISSUE TITLE
Custom Rpc and Console Rpc alway turn on/off at the same time

### ISSUE THREAD

**Issue by DemoVPS69420** [dead8309/Kizzy#256] opened 2024-03-21 17:49 UTC
Console Rpc keep turn on/off when i turn on/off Custom Rpc

 - Device: Lenovo Legion Y70
 - OS: Android 12
 - Kizzy Version: 5.3

https://cdn.discordapp.com/attachments/811910266560315422/1220428926137139250/screenrecorder-20240322-004831.mp4?ex=660ee802&is=65fc7302&hm=1ff87fc957623ed55356755784f594144523844e47cf94ceb4f3b3149e65b1f8&

**Comment by dead8309** [comment] 2024-04-05 22:04
Duplicate of #91

**Closed by dead8309** 2024-04-05 22:04 UTC
Labels: bug
